CREATE TABLE m.osoba (
  "id" int NOT NULL PRIMARY KEY,
  "osobne_cislo" varchar(10) NOT NULL,
  "meno" varchar(255) NOT NULL,
  "meno2" varchar(255) NOT NULL,
  "meno3" varchar(255) NOT NULL,
  "externe_osobne_cislo" varchar(20) NOT NULL, --externe cislo
  "aktivny" boolean NOT NULL,
  "funkcia" varchar(50) NOT NULL,
  "pozicia" varchar(50) NOT NULL,
  "oddelenie" varchar(20) NOT NULL,
  "pobocka" varchar(20) NOT NULL,
  "stredisko" varchar(10) NOT NULL,
  "tel1" varchar(25) NOT NULL,
  "tel2" varchar(25) NOT NULL,
  "tel3" varchar(25) NOT NULL,
  "skype" varchar(100) NOT NULL,
  "email" varchar(100) NOT NULL,
  "rodne_cislo" varchar(10) NOT NULL,
  "datum_nar" date NOT NULL,
  "pohlavie" char(1) NOT NULL,
  "statna_prislusnost" varchar(20) NOT NULL,
  "miesto_narodenia" varchar(100) NOT NULL,
  "stav" char(1) NOT NULL,
  "obcianky" varchar(25) NOT NULL,
  "pas" varchar(25) NOT NULL,
  "adr11" varchar(100) NOT NULL,
  "adr12" varchar(100) NOT NULL,
  "adr13" varchar(100) NOT NULL,
  "adr14" varchar(100) NOT NULL,
  "adr1psc" varchar(6) NOT NULL,
  "adr1mesto" varchar(100) NOT NULL,
  "adr1okres" varchar(100) NOT NULL,
  "adr1kraj" varchar(100) NOT NULL,
  "adr1krajina" varchar(100) NOT NULL,
  "adr21" varchar(100) NOT NULL,
  "adr22" varchar(100) NOT NULL,
  "adr23" varchar(100) NOT NULL,
  "adr24" varchar(100) NOT NULL,
  "adr2psc" varchar(6) NOT NULL,
  "adr2mesto" varchar(100) NOT NULL,
  "adr2okres" varchar(100) NOT NULL,
  "adr2kraj" varchar(100) NOT NULL,
  "adr2krajina" varchar(100) NOT NULL,
  "nastup" date NOT NULL,
  "ukocenie" date NOT NULL,
  "status" char(1) NULL,
  "pozn" varchar(255) NOT NULL
);


COMMENT ON COLUMN m.osoba.aktivny IS '  udaj oznacuje ci je mozne s danym zaznamom pracovat alebo nie. Nie - nevyberie sa pre spracovanie miezd';
COMMENT ON COLUMN m.osoba.nastup IS '  datum zaciatku pracovneho pomeru';
COMMENT ON COLUMN m.osoba.ukoncenie IS ' datum ukoncenia pracovneho pomeru';
